#!/usr/bin/env bash

TODO_FILE="$HOME/.todo.txt"
strike() {
  local out=""
  local i
  for ((i=0; i<${#1}; i++)); do
    out+="${1:$i:1}̶"
  done
  printf '%s' "$out"
}

doneSound() {
 local sound="$1"
 afplay /System/Library/Sounds/"$sound" &
}


case "$1" in
startup)
RC_FILE="$HOME/.zshrc"
MARKER="# added by todo"
if grep -Fq "$MARKER" "$RC_FILE"; then
 echo "startup already in zshrc"
else 
 cat >> "$RC_FILE" << EOF

$MARKER
echo "heres your todo list today:"
todo
EOF
 echo "Done - open a new terminal to see your list on startup"
fi 
;;
   
 add)
    echo "Add tasks ( Crtl + D when done):"
    while read -r line; do
      [ -n "$line" ] && echo "$line" >> "$TODO_FILE"
    done 
     ;;
today|list)
    nl "$TODO_FILE"
    ;;

done)
TASK=$(sed -n "${2}p" "$TODO_FILE")
  if [ -z "$TASK" ]; then
    echo "No task #$2." >&2; exit 1
  fi

 sed -i.bak "${2}d" "$TODO_FILE" && rm "$TODO_FILE.bak"
 
for frame in "⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏"; do
    printf "\r  %s  %s" "$frame" "$TASK"
    sleep 0.005
  done

printf "\r  \033[32m✓  %s\033[0m\n" "$(strike "$TASK")"
doneSound "Frog.aiff"
REMAINING=$(wc -l < "$TODO_FILE" | tr -d ' ')
printf "  %s left.\n" "$REMAINING"
 ;;

"") 
    nl "$TODO_FILE"
    ;;
help)
 echo "todo <item to add>"
;;

 *)
   echo "$@" >> "$TODO_FILE"
   echo "added: $@"
   ;;

esac


