#!/usr/bin/env bash

TODO_FILE="$HOME/.todo.txt"


case "$1" in
startup)
RC_FILE="$HOME/.zshrc"
MARKER="# added by todo"
if grep -Fq "$MARKER" "$RC_FILE"; then
 echo "startup already in zshrc"
else 
 cat >> "$RC_FILE" << EOF

$MARKER
echo "heres your todo list today:"
todo
EOF
 echo "Done - open a new terminal to see your list on startup"
fi 
;;
   
 add)
    echo "Add tasks ( Crtl + D when done):"
    while read -r line; do
      [ -n "$line" ] && echo "$line" >> "$TODO_FILE"
    done 
     ;;
today|list)
    nl "$TODO_FILE"
    ;;

done)
 sed -i.bak "${2}d" "$TODO_FILE" && rm "$TODO_FILE.bak"
 echo "item cleared"
 echo "list:"
 todo 
 ;;

"") 
    nl "$TODO_FILE"
    ;;

 *)
   echo "$@" >> "$TODO_FILE"
   echo "added: $@"
   ;;

esac


